### ISSUE TITLE
runnng as a module

### ISSUE THREAD

**Issue by AnnaMag** [shoebot/shoebot#109]
I'm running

import shoebot
bot = shoebot.bot(outputfile="output.svg")
bot.size(640, 480)
bot.rect(10, 10, 100, 100)
bot.finish()

as a standalone script (I tried IPython notebook also) and get:

File "scripts/example.py", line 6, in <module>
    bot = shoebot.bot(outputfile="output.svg")
AttributeError: 'module' object has no attribute 'bot'

how to fix that?

**Comment by stuaxo** [comment]
This part of the API changed slightly in rewrites, changing shoebot.bot to shoebot.create_bot works:

```python
import shoebot
bot = shoebot.create_bot(outputfile="output.svg")
bot.size(640, 480)
bot.rect(10, 10, 100, 100)
bot.finish()
```

I'm guessing the docs aren't up to date somewhere + have the older API ?   Definitely send a patch or let me know where they are wrong.

**Comment by AnnaMag** [comment]
all info I found was erroneous then.. to start with:
https://github.com/shoebot/shoebot/wiki/PythonModule

Where can one find the correct API? (as per example you gave)

Also, having problems with 'ximport'. Any fixes for that?

**Comment by AnnaMag** [comment]
Btw, great work! Precisely what I needed! Almost set up to write it myself and then found Shoebot. 
If there is a write up of the current API, and differences in the use of Shoebot wrt to Nodebox, please point me to the info. I'd like to contribute maybe at some point.

**Comment by AnnaMag** [comment]
No matter which script I run I get 
('Typography not available ', ImportError('No module named pgi',))

Running your example http://www.stuartaxon.com/tag/shoebot/ from within the shoebot directory using Python2.7:

'size(800, 800)
NameError: name 'size' is not defined'

'colours=ximport("colors")
NameError: name 'ximport' is not defined
'

**Comment by tian2992** [comment]
Most things should be similar to Nodebox, however ximport is not used. As far as I remember, colors is imported as-is, but when called via sbot binary (```sbot my_sketch.py```)

**Comment by AnnaMag** [comment]
Could you clarify 'imported as-is', please? Exemplary line?

How about the 'size' Error?

**Comment by stuaxo** [comment]
> No matter which script I run I get
> ('Typography not available ', ImportError('No module named pgi',))

The 'No module named pgi' error could be more helpful - it's saying it can't find 'gi' - used for GUI under Gtk3.

Hopefully this message  #110   would be more helpful ?


> "Typography not available"

This is a bug - that should only display if you run under pypy and have pgi installed.



> 'size(800, 800)
> NameError: name 'size' is not defined'

Looks like you are running the script with ```python ...``` not ```sbot ...``` ?
- I need to add a note to any shoebot examples on my site on how to run them.


You probably want something like:

```python
sbot -w granuals.bot
```

> If there is a write up of the current API, and differences in the use of Shoebot wrt to Nodebox, please > point me to the info.

This needs writing up - in summary:

- Shoebot aims to support all of the nodebox API missing parts are bugs.
- Shoebot extends APIs where it won't break Nodebox code (e.g. "fill" returns the current color).

This  http://shoebot-test-rtd.readthedocs.org/en/latest/commands.html  is the best example right now, but is a little out of date.  - RTD didn't work for us for ages, but now it does I need to update it (we can even embed bits of shoebot code in it). 

#111


Things shoebot does not include / do:

- geometry lib:    
This has a nonstandard license.... possibly we should just include it though, since we have a mix of licenses already.
- support for mac specific stuff (some Nodebox bots dig under shoebot and use qwartz).

**Comment by rlafuente** [comment]
@AnnaMag, thank you for your thorough patience and useful bug reports, and apologies for the contradictory docs! I've tried and edited some sections for clarity. Is [this](https://github.com/shoebot/shoebot/blob/master/doc/source/hacking.rst) better?

@stuaxo I forgot how to update ReadTheDocs :p also, since the Python module docs are now clearer, maybe we can get rid of the redundant wiki pages like https://github.com/shoebot/shoebot/wiki/PythonModule?

**Comment by AnnaMag** [comment]
@rlafuente , @stuaxo Thanks for being so responsive!
