### ISSUE TITLE
We should default to pycairo not cairocffi

### ISSUE THREAD

**Issue by stuaxo** [shoebot/shoebot#136]
The original reasons for supporting cairocffi as well as pycairo don't stand up.

- pycairo is now being updated so has newer features (we needed cairocffi for recording surface)
- cairocffi is still faster on pypy, but pycairo does work there.
- gi.repository now works in pypy too !

CairoCFFI and PGI complicate things
- pango support is not quite there
- pgi doesn't support inheritance, and there are some other incompatibilities.

On the other hand, switching between these has been such a pain each time, it might be worth taking a step back and working trying a couple of different solutions before doing anything.

**Comment by rlafuente** [comment]
I agree that this transition is a low-priority goal. 

Right now stuff seems to fully work, and the problem exposed in #132 is easily fixed with the `--disable-background-thread` flag.

It would be nice to eventually move back to Pycairo, which would help simplify the code base and get Pango working nicely. I can give it a shot if it's not too complex...

**Comment by stuaxo** [comment]
Did a quick test and this should be as simple as swapping out cairocffi for pycairo in ```requirements.txt```.

Probably worth updating other requirements too (but leave meta unversioned.

**Comment by stuaxo** [comment]
OK, turns out that was clearly nonsense :)

We're reliant on having cairocffi and pycairo, it's not ideal.

**Comment by stuaxo** [comment]
Done in the backend issue
