### ISSUE TITLE
Missing package in install_dependencies.sh for Darwin?

### ISSUE THREAD

**Issue by dreerr** [shoebot/shoebot#137]
Please correct me if I'm wrong but I spent the whole day yesterday trying to install shoebot and I think the problem was that the Homebrew package named `pygobject`was missing. Instead I accidentally installed the eponymous package via `pip install gi` which apparently is something different [https://pypi.org/project/gi/](https://pypi.org/project/gi/)

**Comment by rlafuente** [comment]
Good find, indeed gobject is missing from the dependency install script. From [this](https://stackoverflow.com/a/33192698/122400) I guess that we should just add `pygobject3` to the list of Homebrew packages, is this right?

(btw, please do keep filing issues as you find them, since feedback on OSX operation is really useful for us!)

**Comment by dreerr** [comment]
Yes you are right! I was at that exact page because I apparently failed gi.repository in diagnose. 
Cool, I will keep filing! Used to switch from NodeBox to PlotDevice, now to Shoebot, because of speed and possible platform independence. Thank you so much for this project!

**Comment by rlafuente** [comment]
Fantastic :-) Thank you for the great feedback!
