### ISSUE TITLE
Our index.html is an index, not necessarily a good frontpage/landing page.

### ISSUE THREAD

**Issue by stuaxo** [shoebot/shoebot#160]
index.html is a literal index of content

http://shoebot.readthedocs.io/en/latest/

This isn't necessarily the best kind of front-page for our docs

I've been using a lot of python projects recently, and my favorites:
- Tell you what they are
- Have small code examples + screenshots demonstrating how awsome they are on their landing page.

The worst offenders, say things like "Frob" is an implementation of "Baa", when you click to "Baa" it tells you it is a "Thingathing" etc.

We're not as bad as this, but it would be easy given the complex family tree.

Our strengths are the simplicity of our code and our nice vector based output, we should be showing these off.

This ticket is a little vague - I'll try and link in good + bad examples if I get time.

**Comment by rlafuente** [comment]
100% agree! I've tried to rewrite most of the docs but left the index page untouched. 

I've tried to follow other projects' docs for inspiration on structure (I like [Pelican](http://pelican.readthedocs.org)) but I'm always hesitant on going ahead and redoing whole parts. But this issue is a good push forward.

So for starters, maybe this could be a good start for a fix:

- rewrite the Introduction section, with less text and more relevant info. Linking to Nodebox/Drawbot docs is better than trying to re-explain all ideas of generative design.
- move the Introduction contents to the index page
- delete Introduction page

For code examples:

- take some 5-6 better-looking scripts and place them in the Examples page
- make small screenshots and place then on the Index, each linking to its section in Examples

This would go a long way in fixing the Index to become welcoming, and maybe actually replace the shoebot.net root page, which kind of plays the same role now.

**Comment by stuaxo** [comment]
This is much better, saying what we are is a great start.

For examples, I'm hoping the cleanup of the plugin-api makes it easy to do things like generate a gallery of all/some of the examples, things are getting there, it's getting the hours to do it is the tricky bit :)

**Comment by rlafuente** [comment]
BTW I added #167 to follow the examples part
