### ISSUE TITLE
LGM discussion

### ISSUE THREAD

**Issue by stuaxo** [shoebot/shoebot#191]
Meta ticket for LGM discussion

- [ ] Make a place to collect peoples contributions.
- Review docs
   - Installation
      - [ ] Clearer sections for Quickstart (simple system wide install) and 
      - [ ] Other Methods (virtualenvwrapper, pipenv)

**Comment by stuaxo** [comment]
Lol, re: fun tasks, I read something that people with boring jobs are doomed to come with boring things to do, maybe without creative coding at work, I'm doomed to develop the boring stuff :rofl:

**Comment by rlafuente** [comment]
Great idea to have a meta ticket for this! Jotting down some thoughts

### Conclusions from the 2014 workshop

* It worked great since the LGM audience, who already were familiar with creative coding and Python hacking
* people were able to get things running quickly
* the experiments made in the workshop all worked great as examples to be added to Shoebot. I added some, but I did a bad job of gathering everyone's contributions and some got lost in the process
* it was a missed opportunity to get people more involved, e.g. joining the mailing list or IRC channel

### Things to keep in mind / TODO

* Ensure that the docs are clear when it comes to installing, the [install page](https://shoebot.readthedocs.io/en/latest/install.html) probably needs a review.
  * Clearer sections for Quickstart (simple system wide install) and Other Methods (virtualenvwrapper, pipenv)
* I think Jupyter notebooks would be a great way to do an introductory demo of static stuff, but we should show how to use a supported text editor too -- Xed? for the livecoding part
* I could bring a MIDI interface in case that's useful for demoing the livecoding stuff.

Will probably dump a few more but for the moment I won't flood this too much.

**Comment by stuaxo** [comment]
> Great idea to have a meta ticket for this! Jotting down some thoughts
> ### Conclusions from the 2014 workshop
> 
>     * It worked great since the LGM audience, who already were familiar with creative coding and Python hacking
> 
>     * people were able to get things running quickly
> 
>     * the experiments made in the workshop all worked great as examples to be added to Shoebot. I added some, but I did a bad job of gathering everyone's contributions and some got lost in the process
> 
>     * it was a missed opportunity to get people more involved, e.g. joining the mailing list or IRC channel
> 
Definitely documenting them, and having a something like a short check list to mark this off with makes sense.

> ### Things to keep in mind / TODO
> 
>     * Ensure that the docs are clear when it comes to installing, the [install page](https://shoebot.readthedocs.io/en/latest/install.html) probably needs a review.
>       
The temptation to start fresh with components that play well with pip is strong, but I will try and resist :lol:

>       * Clearer sections for Quickstart (simple system wide install) and Other Methods (virtualenvwrapper, pipenv)
> 
>     * I think Jupyter notebooks would be a great way to do an introductory demo of static stuff, but we should show how to use a supported text editor too -- Xed? for the livecoding part
> 
>     * I could bring a MIDI interface in case that's useful for demoing the livecoding stuff.
> 
Sounds like fun, I got some fun with python and MIDO (not shoebot based).
Do we have any MIDI examples, if not MIDO makes it super easy, we'd want one to start them off with.

> 
> Will probably dump a few more but for the moment I won't flood this too much.

I am pretty guilty of flooding, what with my lack of focus :)

**Comment by rlafuente** [comment]
> The temptation to start fresh with components that play well with pip is strong, but I will try and resist :lol:

I agree here! I'm all for simplifying the installation process (maybe a new branch if you want a go at it?) but for the workshop we really want to cut down on the open tasks since we're both strapped for time and when we know it, LGM is next week :)

> Sounds like fun, I got some fun with python and MIDO (not shoebot based).
> Do we have any MIDI examples, if not MIDO makes it super easy, we'd want one to start them off with.

Hey, that's really cool that you already got it working! I'm def bringing the MIDI pad, at the very least I'd love to get it working on my PC!

> I am pretty guilty of flooding, what with my lack of focus :)

I too am guilty of not being able to focus properly, with all the little tasks that spread in so many problem areas that it's really hard not to drift...

**Comment by stuaxo** [comment]
Moving to gi.RSVG seems like a must, it looks like the non-gobject version is being dropped (at least from Ubuntu).
https://github.com/shoebot/shoebot/issues/199

Possibly only a 3 line change though.

**Comment by stuaxo** [comment]
What's the real MVP we need for a next small release - with stuff like installation fixes + current docs ?
(I'd like to get the bigger changes ready before LGM and do another larger release when they're ready).

I'd say:  

- fix the RSVG bug above.
- make OSX not use the background thread.

Anything else ?

**Comment by stuaxo** [comment]
Moving the conversation about the next release to here:  https://github.com/shoebot/shoebot/issues/202

**Comment by stuaxo** [comment]
Back on LGM conversation:

I've got one MIDI interface with a bunch of sliders and buttons, and getting a small MIDI keyboard - any ideas on what we could do MIDI-wise ?

If the jupyter stuff is working this is another possible avenue to go down.

I like the idea of doing something with texture - we're good at making vector graphics, but combining the clean world of vectors with different textures seems interesting to me.
